Repository AY2021S2-CS2103T-T12-4/tp, pull requests merged in 2021-02, with the labels that each got.

#41 Docs: update readme template with team and product information
  docs/AboutUs.md
Labels: priority.High

#42 Docs: update some commands of User Guide
  docs/UserGuide.md
Labels: priority.High

#45 Chore: add script to easily sync repositories
  scripts/sync.sh
Labels: priority.Low

#50 Docs: update tjtanjin section for AboutUs and add profile image
  docs/AboutUs.md
  docs/images/tjtanjin.png
Labels: priority.High

#53 Docs: update Yongliang section for AboutUs and add profile image, and portfolio
  docs/AboutUs.md
  docs/images/tlylt.png
  docs/team/tlylt.md
Labels: priority.High

#55 Clean up DeveloperGuide to only include requirements
  docs/DeveloperGuide.md
Labels: priority.High

#52 Docs: add send command to UserGuide
  docs/UserGuide.md
Labels: priority.High

#56 Docs: update ong6 section for AboutUs and update README
  .gitignore
  .project
  README.md
  docs/AboutUs.md
  docs/images/ong6.png
  docs/team/julietteoh.md
  docs/team/ong6.md
Labels: priority.High

#62 Update developer guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Task

#64 Docs: update user guide and developer guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#68 Docs: add initial template for tjtanjin personal portfolio
  docs/team/tjtanjin.md
Labels: priority.High

#66 Docs: add workflow guide and imposter icon
  docs/WorkflowGuide.md
  docs/images/ImPoster.png
Labels: priority.High

#71 Docs: update developer guide and add user stories and use cases
  docs/DeveloperGuide.md
Labels: priority.High

#73 Docs: reduce imposter icon size to 300px
  docs/WorkflowGuide.md
Labels: priority.Medium

#75 Feat: add template for send command, full logic to be integrated with…
  src/main/java/seedu/address/logic/api/EndpointCaller.java
  src/main/java/seedu/address/logic/commands/SendCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SendCommandParser.java
Labels: priority.High, type.Task

#84 Docs: update _config.yml with imposter information
  docs/_config.yml
Labels: priority.High

#81 Docs: update userguide phrasing and features
  docs/UserGuide.md
Labels: priority.High
