Repository AY2021S2-CS2103T-T12-4/tp, pull requests merged in 2021-03, with the labels that each got.

#82 Docs: complete AboutUs
  docs/AboutUs.md
  docs/images/nightraven49.png
  docs/team/nightraven49.md
Labels: priority.High

#96 Docs: minor description update and rectify user guide link
  README.md
  src/main/java/seedu/us/among/logic/parser/ImposterParser.java
  src/test/java/seedu/us/among/logic/LogicManagerTest.java
Labels: priority.High

#86 Docs: update all instances of ImPoster to imPoster
  build.gradle
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  docs/WorkflowGuide.md
  docs/team/ong6.md
  docs/team/tjtanjin.md
  docs/team/tlylt.md
  src/main/java/seedu/us/among/ImPoster.java
  src/main/java/seedu/us/among/Main.java
  src/main/java/seedu/us/among/logic/commands/ExitCommand.java
  src/main/java/seedu/us/among/model/ModelManager.java
  src/main/resources/view/MainWindow.fxml
  src/test/data/JsonSerializableEndpointListTest/typicalEndpointList.json
Labels: priority.High

#98 Chore: add githook to ensure checkstyle and test passes locally before commit
  .githooks/pre-commit
Labels: priority.Medium

#100 Docs: update index to correctly show product information on main webpage
  docs/index.md
Labels: priority.High

#93 Refactor: Remove phone and email from codebase
  src/main/java/seedu/us/among/logic/commands/AddCommand.java
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/logic/parser/AddCommandParser.java
  src/main/java/seedu/us/among/logic/parser/CliSyntax.java
  src/main/java/seedu/us/among/logic/parser/EditCommandParser.java
  src/main/java/seedu/us/among/logic/parser/ParserUtil.java
  src/main/java/seedu/us/among/model/endpoint/Email.java
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
  src/main/java/seedu/us/among/model/endpoint/Phone.java
  src/main/java/seedu/us/among/model/util/SampleDataUtil.java
  src/main/java/seedu/us/among/storage/JsonAdaptedEndpoint.java
  src/main/java/seedu/us/among/ui/EndpointCard.java
  src/main/resources/view/EndpointListCard.fxml
  src/test/data/JsonEndpointListStorageTest/invalidAndValidEndpointList.json
  src/test/data/JsonEndpointListStorageTest/invalidEndpointList.json
  src/test/data/JsonSerializableEndpointListTest/duplicateEndpointList.json
  src/test/data/JsonSerializableEndpointListTest/invalidEndpointList.json
  src/test/data/JsonSerializableEndpointListTest/typicalEndpointList.json
  src/test/java/seedu/us/among/logic/LogicManagerTest.java
  src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
  src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
  src/test/java/seedu/us/among/logic/commands/EditEndpointDescriptorTest.java
  src/test/java/seedu/us/among/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/ParserUtilTest.java
  src/test/java/seedu/us/among/model/endpoint/EmailTest.java
  src/test/java/seedu/us/among/model/endpoint/EndpointTest.java
  src/test/java/seedu/us/among/model/endpoint/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/us/among/model/endpoint/PhoneTest.java
  src/test/java/seedu/us/among/storage/JsonAdaptedEndpointTest.java
  src/test/java/seedu/us/among/testutil/EditEndpointDescriptorBuilder.java
  src/test/java/seedu/us/among/testutil/EndpointBuilder.java
  src/test/java/seedu/us/among/testutil/EndpointUtil.java
  src/test/java/seedu/us/among/testutil/TypicalEndpoints.java
Labels: priority.High

#102 Docs: tidy up and update developer guide
  docs/DeveloperGuide.md
Labels: priority.High

#104 Docs: tidy up and update user guide
  docs/UserGuide.md
Labels: priority.High

#108 Docs: rename imposter images
  docs/images/imPoster.png
  docs/images/imPosterB.png
  src/main/java/seedu/us/among/ui/UiManager.java
  src/main/resources/images/imPoster.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/us/among/commons/util/AppUtilTest.java
Labels: priority.High

#110 Docs: tidy up about us and update tjtanjin image
  docs/AboutUs.md
  docs/images/tjtanjin.png
Labels: priority.High

#106 Docs: Update Readme
  README.md
Labels: priority.High

#114 Update UI image
  docs/images/Ui.png
Labels: priority.High, type.Task

#117 Docs: resize imposter icon and centralise badges
  README.md
Labels: priority.High

#120 Refactor: update build.gradle to reflect new package name
  build.gradle
Labels: priority.High

#121 Fix minor syntax issues within readme & docs
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: priority.High

#122 Commands: AddCommand update
  .vscode/settings.json
  docs/tutorials/TracingCode.md
  src/main/java/seedu/us/among/logic/commands/AddCommand.java
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/logic/parser/AddCommandParser.java
  src/main/java/seedu/us/among/logic/parser/CliSyntax.java
  src/main/java/seedu/us/among/logic/parser/EditCommandParser.java
  src/main/java/seedu/us/among/logic/parser/ParserUtil.java
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
  src/main/java/seedu/us/among/model/endpoint/Method.java
  src/main/java/seedu/us/among/model/endpoint/MethodType.java
  src/main/java/seedu/us/among/model/endpoint/Name.java
  src/main/java/seedu/us/among/model/endpoint/NameContainsKeywordsPredicate.java
  src/main/java/seedu/us/among/model/endpoint/UniqueEndpointList.java
  src/main/java/seedu/us/among/model/util/SampleDataUtil.java
  src/main/java/seedu/us/among/storage/JsonAdaptedEndpoint.java
  src/main/java/seedu/us/among/ui/EndpointCard.java
  src/test/data/JsonSerializableEndpointListTest/duplicateEndpointList.json
  src/test/data/JsonSerializableEndpointListTest/typicalEndpointList.json
  src/test/java/seedu/us/among/logic/LogicManagerTest.java
  src/test/java/seedu/us/among/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/us/among/logic/commands/AddCommandTest.java
  src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
  src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
  src/test/java/seedu/us/among/logic/commands/EditEndpointDescriptorTest.java
  src/test/java/seedu/us/among/logic/commands/FindCommandTest.java
  src/test/java/seedu/us/among/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/FindCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/ImposterParserTest.java
  src/test/java/seedu/us/among/logic/parser/ParserUtilTest.java
  src/test/java/seedu/us/among/model/EndpointListTest.java
  src/test/java/seedu/us/among/model/ModelManagerTest.java
  src/test/java/seedu/us/among/model/endpoint/EndpointTest.java
  src/test/java/seedu/us/among/model/endpoint/MethodTest.java
  src/test/java/seedu/us/among/model/endpoint/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/us/among/model/endpoint/NameTest.java
  src/test/java/seedu/us/among/model/endpoint/UniqueEndpointListTest.java
  src/test/java/seedu/us/among/storage/JsonAdaptedEndpointTest.java
  src/test/java/seedu/us/among/storage/JsonEndpointListStorageTest.java
  src/test/java/seedu/us/among/storage/JsonSerializableEndpointListTest.java
  src/test/java/seedu/us/among/testutil/EditEndpointDescriptorBuilder.java
  src/test/java/seedu/us/among/testutil/EndpointBuilder.java
  src/test/java/seedu/us/among/testutil/EndpointUtil.java
  src/test/java/seedu/us/among/testutil/TypicalEndpoints.java
Labels: priority.High

#125 Feat: add API call feature
  build.gradle
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
  src/main/java/seedu/us/among/model/endpoint/Response.java
  src/main/java/seedu/us/among/model/util/SampleDataUtil.java
  src/main/java/seedu/us/among/storage/JsonAdaptedEndpoint.java
  src/main/java/seedu/us/among/storage/JsonAdaptedResponse.java
  src/test/java/seedu/us/among/storage/JsonAdaptedEndpointTest.java
Labels: priority.High

#127 Bug: Fix test cases
  docs/TestsToFix.txt
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
  src/main/java/seedu/us/among/model/endpoint/UniqueEndpointList.java
  src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
  src/test/java/seedu/us/among/model/EndpointListTest.java
  src/test/java/seedu/us/among/model/endpoint/EndpointTest.java
  src/test/java/seedu/us/among/model/endpoint/UniqueEndpointListTest.java
Labels: priority.High

#132 Feat: add basic template for new UI
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#129 Refactor: tidy up code for making requests and remove placeholders
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
  src/main/java/seedu/us/among/logic/endpoint/GetRequest.java
  src/main/java/seedu/us/among/logic/endpoint/Request.java
Labels: priority.High

#136 Update WorkflowGuide
  docs/WorkflowGuide.md
Labels: priority.High

#137 Add time taken as an attribute of response
  src/main/java/seedu/us/among/logic/endpoint/GetRequest.java
  src/main/java/seedu/us/among/model/endpoint/Response.java
  src/main/java/seedu/us/among/storage/JsonAdaptedEndpoint.java
  src/main/java/seedu/us/among/storage/JsonAdaptedResponse.java
Labels: priority.High

#142 Refactor response to store and display pretty printed json string
  src/main/java/seedu/us/among/commons/util/JsonUtil.java
  src/main/java/seedu/us/among/logic/endpoint/GetRequest.java
Labels: priority.High

#143 Display result update
  src/main/java/seedu/us/among/commons/util/StringUtil.java
  src/main/java/seedu/us/among/logic/commands/CommandResult.java
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/endpoint/GetRequest.java
  src/main/java/seedu/us/among/model/endpoint/Response.java
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/main/java/seedu/us/among/ui/ResultDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.High

#146 Feat: add thread to handle UI update for showing command execution progress
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
  src/main/java/seedu/us/among/ui/CommandBox.java
  src/main/java/seedu/us/among/ui/EndpointListPanel.java
  src/main/java/seedu/us/among/ui/MainWindow.java
Labels: priority.High

#160 Fix response time saving bug
  src/main/java/seedu/us/among/commons/util/StringUtil.java
  src/main/java/seedu/us/among/logic/endpoint/GetRequest.java
  src/main/java/seedu/us/among/model/endpoint/Response.java
Labels: priority.High

#161 Fix: fix exit command bug along with ui lag and spam input
  src/main/java/seedu/us/among/ui/CommandBox.java
  src/main/java/seedu/us/among/ui/EndpointListPanel.java
  src/main/java/seedu/us/among/ui/MainWindow.java
Labels: priority.High

#164 Fix issue of help-window not opening for help command
  src/main/java/seedu/us/among/ui/MainWindow.java
Labels: priority.High

#166 Refactor: replace UI threading update with animated gif and improve performance
  src/main/java/seedu/us/among/ui/CommandBox.java
  src/main/java/seedu/us/among/ui/HelpWindow.java
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/main/java/seedu/us/among/ui/ResultDisplay.java
  src/main/resources/images/error.gif
  src/main/resources/images/loading_spinner.gif
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.High

#168 Feat: add support for post request
  src/main/java/seedu/us/among/commons/util/HeaderUtil.java
  src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
  src/main/java/seedu/us/among/logic/endpoint/GetRequest.java
  src/main/java/seedu/us/among/logic/endpoint/PostRequest.java
  src/main/java/seedu/us/among/logic/endpoint/Request.java
Labels: priority.High

#170 Fix text wrap and add command invalid message
  src/main/java/seedu/us/among/logic/commands/AddCommand.java
  src/main/java/seedu/us/among/ui/ResultDisplay.java
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.High

#173 Update user guide to use realistic api urls
  docs/UserGuide.md
  docs/WorkflowGuide.md
  src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
Labels: priority.High

#174 Fix sample data for first time users
  src/main/java/seedu/us/among/model/util/SampleDataUtil.java
Labels: priority.High

#177 Fix: fix a bug where command box is not auto-focused after send command
  src/main/java/seedu/us/among/ui/CommandBox.java
Labels: priority.High

#179 Fix: fix bug with post request body data not being sent
  src/main/java/seedu/us/among/logic/endpoint/Request.java
Labels: priority.High

#183 Refactor: update sample data with more examples
  src/main/java/seedu/us/among/model/util/SampleDataUtil.java
Labels: priority.High

#185 Feat: add different color to response meta based on status code
  src/main/java/seedu/us/among/ui/ResultDisplay.java
Labels: priority.Medium

#189 Fix: add handling of exceptions when sending request
  src/main/java/seedu/us/among/logic/Logic.java
  src/main/java/seedu/us/among/logic/LogicManager.java
  src/main/java/seedu/us/among/logic/commands/Command.java
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/endpoint/Request.java
  src/main/java/seedu/us/among/logic/endpoint/exceptions/RequestException.java
  src/main/java/seedu/us/among/ui/CommandBox.java
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/test/java/seedu/us/among/logic/LogicManagerTest.java
  src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
Labels: priority.High

#192 Fix: add proper catch for html response
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/endpoint/Request.java
Labels: priority.High

#199 Include workflow guide
  docs/DeveloperGuide.md
  docs/WorkflowGuide.md
Labels: priority.Medium

#200 Fix: add a check when parsing headers and catch invalid headers
  src/main/java/seedu/us/among/commons/util/HeaderUtil.java
  src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
  src/main/java/seedu/us/among/logic/endpoint/GetRequest.java
  src/main/java/seedu/us/among/logic/endpoint/PostRequest.java
  src/main/java/seedu/us/among/logic/endpoint/Request.java
Labels: priority.High

#204 Model and Commands: Wrapped things up and fixed many bugs.
  src/main/java/seedu/us/among/commons/util/HeaderUtil.java
  src/main/java/seedu/us/among/logic/commands/AddCommand.java
  src/main/java/seedu/us/among/logic/parser/AddCommandParser.java
  src/main/java/seedu/us/among/logic/parser/CliSyntax.java
  src/main/java/seedu/us/among/logic/parser/ImposterParser.java
  src/main/java/seedu/us/among/logic/parser/ParserUtil.java
  src/main/java/seedu/us/among/model/endpoint/Data.java
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
  src/main/java/seedu/us/among/model/endpoint/header/Header.java
  src/main/java/seedu/us/among/model/tag/Tag.java
  src/main/java/seedu/us/among/ui/CommandBox.java
  src/main/java/seedu/us/among/ui/EndpointCard.java
  src/test/java/seedu/us/among/testutil/TypicalEndpoints.java
Labels: priority.High

#206 Refactor: extend result display instead of having extra right panel in UI
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.Medium

#211 Add RunCommand ability
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/java/seedu/us/among/logic/parser/ImposterParser.java
  src/main/java/seedu/us/among/logic/parser/RunCommandParser.java
Labels: priority.High, severity.High, type.Task

#207 Feat: add support for delete request
  src/main/java/seedu/us/among/logic/endpoint/DeleteRequest.java
  src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
Labels: priority.High

#212 Feat: add keyboard shortcut for user to cancel request
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/endpoint/Request.java
  src/main/java/seedu/us/among/ui/MainWindow.java
Labels: priority.High

#214 Feat: add icon to show up on dock/taskbar
  src/main/java/seedu/us/among/Main.java
  src/main/resources/images/imPosterDock.png
Labels: priority.Low

#215 Find command: Basic Functionality
  src/main/java/seedu/us/among/commons/util/StringUtil.java
  src/main/java/seedu/us/among/logic/commands/AddCommand.java
  src/main/java/seedu/us/among/logic/parser/EditCommandParser.java
  src/main/java/seedu/us/among/model/endpoint/NameContainsKeywordsPredicate.java
  src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
  src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
  src/test/java/seedu/us/among/logic/commands/ListCommandTest.java
  src/test/java/seedu/us/among/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/us/among/testutil/EditEndpointDescriptorBuilder.java
Labels: priority.High

#221 Fix: fix mismatched exceptions for request errors
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
Labels: priority.Medium

#223 Refactor: Request related code
  src/main/java/seedu/us/among/logic/commands/AddCommand.java
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/endpoint/DeleteRequest.java
  src/main/java/seedu/us/among/logic/endpoint/GetRequest.java
  src/main/java/seedu/us/among/logic/endpoint/PostRequest.java
  src/main/java/seedu/us/among/logic/endpoint/Request.java
  src/main/java/seedu/us/among/model/util/SampleDataUtil.java
Labels: priority.High

#227 Add show command
  src/main/java/seedu/us/among/logic/commands/ShowCommand.java
  src/main/java/seedu/us/among/logic/parser/ImposterParser.java
  src/main/java/seedu/us/among/logic/parser/ShowCommandParser.java
  src/test/java/seedu/us/among/logic/commands/ShowCommandTest.java
  src/test/java/seedu/us/among/logic/parser/ShowCommandParserTest.java
Labels: priority.High, severity.High, type.Story

#230 Refactor: change ctrl + c event to be captured only during api call
  src/main/java/seedu/us/among/ui/CommandBox.java
  src/main/java/seedu/us/among/ui/MainWindow.java
Labels: priority.High

#232 Feat: add support for put request
  src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
  src/main/java/seedu/us/among/logic/endpoint/PutRequest.java
  src/main/java/seedu/us/among/logic/endpoint/Request.java
Labels: priority.High

#235 Fix display of endpoint and response
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
  src/main/java/seedu/us/among/model/endpoint/Response.java
Labels: priority.High

#234 Refactor request related code
  src/main/java/seedu/us/among/commons/util/HeaderUtil.java
  src/main/java/seedu/us/among/logic/endpoint/DeleteRequest.java
  src/main/java/seedu/us/among/logic/endpoint/GetRequest.java
  src/main/java/seedu/us/among/logic/endpoint/PostRequest.java
  src/main/java/seedu/us/among/logic/endpoint/PutRequest.java
  src/main/java/seedu/us/among/logic/endpoint/Request.java
Labels: priority.High

#236 Add test for RunCommand & RunCommandParser
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/java/seedu/us/among/model/util/SampleDataUtil.java
  src/test/java/seedu/us/among/logic/commands/RunCommandTest.java
  src/test/java/seedu/us/among/logic/parser/RunCommandParserTest.java
Labels: priority.High

#239 Feat: add toggle command for user to switch theme
  src/main/java/seedu/us/among/commons/util/StringUtil.java
  src/main/java/seedu/us/among/logic/commands/CommandResult.java
  src/main/java/seedu/us/among/logic/commands/ToggleCommand.java
  src/main/java/seedu/us/among/logic/parser/ImposterParser.java
  src/main/java/seedu/us/among/logic/parser/ToggleCommandParser.java
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/main/java/seedu/us/among/ui/ThemeType.java
  src/main/resources/view/LightTheme.css
Labels: priority.Medium

#246 Fix: minor refactor and fix bug with cancelling requests
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/endpoint/Request.java
  src/main/java/seedu/us/among/ui/CommandBox.java
Labels: priority.High

#243 Docs: update readme with latest information
  README.md
  docs/images/startscreen.png
Labels: priority.Medium

#249 Refactor: tidy up code to improve enum code readability and efficiency
  src/main/java/seedu/us/among/logic/parser/ToggleCommandParser.java
  src/main/java/seedu/us/among/model/endpoint/Method.java
  src/main/java/seedu/us/among/model/endpoint/MethodType.java
  src/main/java/seedu/us/among/ui/ThemeType.java
Labels: priority.Low

#250 Chore: add test cases for SendCommand and SendCommandParser
  src/main/java/seedu/us/among/logic/parser/SendCommandParser.java
  src/main/java/seedu/us/among/model/util/SampleDataUtil.java
  src/test/java/seedu/us/among/logic/commands/SendCommandTest.java
  src/test/java/seedu/us/among/logic/parser/SendCommandParserTest.java
  src/test/java/seedu/us/among/testutil/TypicalEndpoints.java
  src/test/java/seedu/us/among/testutil/TypicalIndexes.java
Labels: priority.High

#253 Refactor code for send & run command
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
Labels: priority.Medium

#257 Add show command details in user guide
  docs/UserGuide.md
Labels: priority.High

#260 Add quick run functionality
  docs/UserGuide.md
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/java/seedu/us/among/logic/parser/AddCommandParser.java
  src/main/java/seedu/us/among/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/us/among/logic/parser/ParserUtil.java
  src/main/java/seedu/us/among/logic/parser/RunCommandParser.java
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
  src/test/java/seedu/us/among/logic/parser/ParserUtilTest.java
  src/test/java/seedu/us/among/logic/parser/RunCommandParserTest.java
Labels: priority.High

#259 Fix: fix test cases that have been commented out thus far
  src/main/java/seedu/us/among/commons/util/StringUtil.java
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/logic/parser/ParserUtil.java
  src/main/java/seedu/us/among/model/endpoint/UniqueEndpointList.java
  src/main/java/seedu/us/among/model/endpoint/exceptions/DuplicateApiEndpointException.java
  src/test/data/JsonSerializableEndpointListTest/duplicateEndpointList.json
  src/test/data/JsonSerializableEndpointListTest/typicalEndpointList.json
  src/test/java/seedu/us/among/logic/LogicManagerTest.java
  src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
  src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
  src/test/java/seedu/us/among/logic/commands/FindCommandTest.java
  src/test/java/seedu/us/among/logic/commands/ListCommandTest.java
  src/test/java/seedu/us/among/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/us/among/logic/commands/ToggleCommandTest.java
  src/test/java/seedu/us/among/logic/parser/ImposterParserTest.java
  src/test/java/seedu/us/among/model/EndpointListTest.java
  src/test/java/seedu/us/among/model/endpoint/UniqueEndpointListTest.java
  src/test/java/seedu/us/among/storage/JsonSerializableEndpointListTest.java
  src/test/java/seedu/us/among/testutil/EditEndpointDescriptorBuilder.java
  src/test/java/seedu/us/among/testutil/EndpointBuilder.java
  src/test/java/seedu/us/among/testutil/EndpointUtil.java
  src/test/java/seedu/us/among/testutil/TypicalEndpoints.java
Labels: priority.High

#262 Docs: clean up user guide
  docs/UserGuide.md
Labels: priority.Medium

#261 Refactor: include reasonphrase in response to user
  src/main/java/seedu/us/among/ui/ResultDisplay.java
Labels: priority.Medium

#263 Fix edit command error msg
  src/main/java/seedu/us/among/logic/commands/AddCommand.java
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/java/seedu/us/among/logic/parser/CliSyntax.java
  src/test/java/seedu/us/among/testutil/EndpointUtil.java
Labels: priority.Medium

#265 Chore: add test cases for ToggleCommandParser
  src/test/java/seedu/us/among/logic/parser/ToggleCommandParserTest.java
Labels: priority.High

#270 Add attributes test
  src/test/java/seedu/us/among/model/endpoint/DataTest.java
  src/test/java/seedu/us/among/model/endpoint/ResponseTest.java
  src/test/java/seedu/us/among/model/header/HeaderTest.java
  src/test/java/seedu/us/among/model/tag/TagTest.java
Labels: JUST MERGE IT!!!, priority.High

#274 Add remaining requests
  src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
  src/main/java/seedu/us/among/logic/endpoint/HeadRequest.java
  src/main/java/seedu/us/among/logic/endpoint/OptionsRequest.java
  src/main/java/seedu/us/among/logic/endpoint/PatchRequest.java
Labels: JUST MERGE IT!!!, priority.High

#272 Fix test cases mainly in AddCommandPaserTest and EditCommandPaserTest
  src/test/java/seedu/us/among/logic/LogicManagerTest.java
  src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
  src/test/java/seedu/us/among/logic/commands/EditEndpointDescriptorTest.java
  src/test/java/seedu/us/among/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/EditCommandParserTest.java
Labels: priority.High

#275 Docs: Updated find command
  build.gradle
  docs/UserGuide.md
Labels: JUST MERGE IT!!!, priority.High

#277 Testing: Add test cases
  docs/TestsToFix.txt
  src/main/java/seedu/us/among/storage/JsonAdaptedEndpoint.java
  src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
  src/test/java/seedu/us/among/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/ParserUtilTest.java
  src/test/java/seedu/us/among/model/endpoint/EndpointTest.java
  src/test/java/seedu/us/among/model/endpoint/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/us/among/storage/JsonAdaptedEndpointTest.java
  src/test/java/seedu/us/among/testutil/EndpointUtil.java
Labels: priority.Medium

#279 Chore: add test cases for Request classes
  src/main/java/seedu/us/among/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableEndpointListTest/typicalEndpointList.json
  src/test/java/seedu/us/among/logic/endpoint/DeleteRequestTest.java
  src/test/java/seedu/us/among/logic/endpoint/GetRequestTest.java
  src/test/java/seedu/us/among/logic/endpoint/HeadRequestTest.java
  src/test/java/seedu/us/among/logic/endpoint/OptionsRequestTest.java
  src/test/java/seedu/us/among/logic/endpoint/PatchRequestTest.java
  src/test/java/seedu/us/among/logic/endpoint/PostRequestTest.java
  src/test/java/seedu/us/among/logic/endpoint/PutRequestTest.java
  src/test/java/seedu/us/among/testutil/TypicalEndpoints.java
Labels: priority.Medium

#244 Add new background to ResultDisplay
  src/main/java/seedu/us/among/ui/ResultDisplay.java
  src/main/resources/images/background.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.High

#288 Refactor based on Juliet's suggestion on LOD
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/endpoint/EndpointCaller.java
  src/main/java/seedu/us/among/logic/endpoint/Request.java
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
  src/test/java/seedu/us/among/logic/commands/RunCommandTest.java
Labels: JUST MERGE IT!!!, priority.Low

#291 Fix: fix some improper test information and add a few more cases
  src/test/java/seedu/us/among/model/endpoint/AddressTest.java
  src/test/java/seedu/us/among/model/endpoint/DataTest.java
  src/test/java/seedu/us/among/model/endpoint/MethodTest.java
  src/test/java/seedu/us/among/model/header/HeaderTest.java
  src/test/java/seedu/us/among/model/tag/TagTest.java
Labels: priority.Medium

#292 Model update: Data only takes in Json
  docs/UserGuide.md
  src/main/java/seedu/us/among/model/endpoint/Data.java
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
Labels: JUST MERGE IT!!!, priority.High

#294 Fix: fix extra time field in response meta
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
  src/main/java/seedu/us/among/ui/ResultDisplay.java
Labels: priority.Medium

#296 Style user guide
  .gitignore
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_includes/head.html
  docs/_includes/header.html
  docs/_layouts/page.html
  docs/_sass/minima/_base.scss
  docs/_sass/minima/_layout.scss
  docs/assets/css/style.scss
  docs/images/Ui.png
  docs/images/favicon.ico
  docs/images/red_box.png
  docs/images/startscreen.png
  docs/index.md
Labels: JUST MERGE IT!!!, priority.High

#299 Adjust ListCommand message
  src/main/java/seedu/us/among/logic/commands/AddCommand.java
  src/main/java/seedu/us/among/logic/commands/ListCommand.java
  src/main/java/seedu/us/among/model/EndpointList.java
  src/main/java/seedu/us/among/model/Model.java
  src/main/java/seedu/us/among/model/ModelManager.java
  src/main/java/seedu/us/among/model/endpoint/UniqueEndpointList.java
  src/main/java/seedu/us/among/ui/EndpointListPanel.java
  src/main/resources/view/EndpointListPanel.fxml
  src/test/java/seedu/us/among/logic/LogicManagerTest.java
  src/test/java/seedu/us/among/logic/commands/AddCommandTest.java
  src/test/java/seedu/us/among/logic/commands/ListCommandTest.java
Labels: JUST MERGE IT!!!, priority.High

#300 Improve help command result
  src/main/java/seedu/us/among/ui/HelpWindow.java
  src/main/java/seedu/us/among/ui/UserGuide.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/us/among/ui/UserGuideTest.java
Labels: priority.High

#303 UI: Improved UI and bug fixes
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/ImposterTheme.css
  src/main/resources/view/LightTheme.css
Labels: JUST MERGE IT!!!, priority.Medium

#304 Defensive send run
  build.gradle
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
Labels: priority.High

#305 Add assert and logging for run and send parsers
  src/main/java/seedu/us/among/logic/commands/ShowCommand.java
  src/main/java/seedu/us/among/logic/parser/RunCommandParser.java
  src/main/java/seedu/us/among/logic/parser/SendCommandParser.java
  src/main/java/seedu/us/among/logic/parser/ShowCommandParser.java
  src/test/java/seedu/us/among/logic/parser/RunCommandParserTest.java
Labels: JUST MERGE IT!!!, priority.High

#308 Added mascot images for user and developer's guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/imPosterDevGuide.png
  docs/images/imPosterUserGuide.png
Labels: priority.Medium

#309 Welcome message
  src/main/java/seedu/us/among/ui/MainWindow.java
Labels: priority.High

#306 UI: Improve UI
  src/main/java/seedu/us/among/ui/ResultDisplay.java
  src/main/resources/images/BackgroundLight-old.png
  src/main/resources/images/BackgroundLight.png
  src/main/resources/images/background.png
  src/main/resources/view/ImposterTheme.css
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.Low

#314 Style user guide
  docs/UserGuide.md
  docs/_layouts/page.html
  docs/_sass/minima/initialize.scss
  docs/assets/css/style.scss
  docs/images/commands/add.png
  docs/images/commands/clear.png
  docs/images/commands/edit.png
  docs/images/commands/find.png
  docs/images/commands/list.png
  docs/images/commands/remove.png
  docs/images/commands/run.png
  docs/images/commands/send.png
  docs/images/commands/show.png
  docs/images/commands/toggle.png
  docs/images/red_box.png
  docs/images/startscreen.png
Labels: priority.High

#315 Developer docs architecture
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/style.puml
  src/main/resources/view/ImposterTheme.css
Labels: JUST MERGE IT!!!, priority.High

#317 Fix: application theme now saves and loads properly
  src/main/java/seedu/us/among/commons/core/GuiSettings.java
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/test/java/seedu/us/among/model/ModelManagerTest.java
  src/test/java/seedu/us/among/storage/JsonUserPrefsStorageTest.java
  src/test/java/seedu/us/among/storage/StorageManagerTest.java
Labels: priority.High

#316 UI: Make headers look like tags
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EndpointListCard.fxml
  src/main/resources/view/ImposterTheme.css
  src/main/resources/view/LightTheme.css
Labels: priority.Low

#319 Fix update of diagram used in developer guide
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/LogicClassDiagram.png
Labels: JUST MERGE IT!!!, priority.High

#321 Updated Find to fix small bug
  src/main/java/seedu/us/among/logic/parser/FindCommandParser.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ImposterTheme.css
Labels: priority.High, type.Bug

#323 Command fixed another small bug with find
  src/main/java/seedu/us/among/logic/parser/FindCommandParser.java
Labels: priority.High, type.Bug

#327 Refactor isSameEndpoint method
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
  src/main/java/seedu/us/among/model/endpoint/UniqueEndpointList.java
  src/test/java/seedu/us/among/logic/commands/AddCommandTest.java
  src/test/java/seedu/us/among/model/endpoint/EndpointTest.java
Labels: priority.High

#328 Fix: error gifs now no longer plays when request is aborted by user
  src/main/java/seedu/us/among/logic/Logic.java
  src/main/java/seedu/us/among/logic/LogicManager.java
  src/main/java/seedu/us/among/logic/commands/Command.java
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/endpoint/exceptions/AbortRequestException.java
  src/main/java/seedu/us/among/ui/CommandBox.java
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/test/java/seedu/us/among/logic/LogicManagerTest.java
  src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
Labels: priority.Low

#335 Fix: fix missed merge conflict
  src/main/java/seedu/us/among/logic/request/exceptions/AbortRequestException.java
Labels: priority.High

#337 Fix: fix invalid url request
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/request/PatchRequest.java
  src/main/java/seedu/us/among/logic/request/PostRequest.java
  src/main/java/seedu/us/among/logic/request/PutRequest.java
  src/main/java/seedu/us/among/logic/request/Request.java
Labels: priority.High

#339 Show & run command coverage
  src/main/java/seedu/us/among/commons/core/Messages.java
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/commands/ShowCommand.java
  src/main/java/seedu/us/among/logic/parser/RunCommandParser.java
  src/test/java/seedu/us/among/logic/commands/RunCommandTest.java
  src/test/java/seedu/us/among/logic/commands/ShowCommandTest.java
Labels: priority.High

#341 Refactor: move exception handling for request into EndpointCaller
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/request/EndpointCaller.java
Labels: priority.High

#338 UI: Add error gif compatible with light theme
  src/main/resources/images/error-light-theme.gif
Labels: priority.Low

#342 Fix: fix error gif text colour in light theme
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/main/java/seedu/us/among/ui/ResultDisplay.java
  src/main/resources/images/error-black.gif
  src/main/resources/images/error-white.gif
Labels: priority.High

#343 Docs: update send & run command in developer guide
  docs/DeveloperGuide.md
  docs/diagrams/RunActivityDiagram.puml
  docs/diagrams/SendSequenceDiagram.puml
  docs/images/RunActivityDiagram.png
  docs/images/SendSequenceDiagram.png
Labels: priority.High

#345 Commands: Address now only takes URL
  src/main/java/seedu/us/among/logic/parser/ParserUtil.java
  src/main/java/seedu/us/among/logic/parser/RunCommandParser.java
  src/main/java/seedu/us/among/model/endpoint/Address.java
  src/test/java/seedu/us/among/logic/parser/ParserUtilTest.java
  src/test/java/seedu/us/among/logic/parser/RunCommandParserTest.java
  src/test/java/seedu/us/among/model/endpoint/AddressTest.java
  src/test/java/seedu/us/among/model/endpoint/MethodContainsKeywordsPredicateTest.java
  src/test/java/seedu/us/among/testutil/EndpointBuilder.java
Labels: priority.High

#349 Chore: update app version in ImPoster
  src/main/java/seedu/us/among/ImPoster.java
Labels: priority.High

#347 Chore: add test cases for Send and Toggle command/parser
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/test/java/seedu/us/among/logic/commands/SendCommandTest.java
  src/test/java/seedu/us/among/logic/commands/ToggleCommandTest.java
  src/test/java/seedu/us/among/logic/parser/SendCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/ToggleCommandParserTest.java
Labels: priority.High

#351 Docs: add request feature implementation to developer guide
  docs/DeveloperGuide.md
  docs/diagrams/RequestActivityDiagram.puml
  docs/diagrams/RequestSequenceDiagram.puml
  docs/diagrams/style.puml
  docs/images/RequestActivityDiagram.png
  docs/images/RequestSequenceDiagram.png
Labels: priority.High

#355 Fix: fix developer guide cover page
  docs/DeveloperGuide.md
Labels: JUST MERGE IT!!!, priority.High

#353 Docs: update user guide appendix
  docs/UserGuide.md
  docs/images/ApiExplanation.png
Labels: priority.High

#359 Minor fix on two sequence diagrams
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/SendSequenceDiagram.puml
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/SendSequenceDiagram.png
Labels: JUST MERGE IT!!!, priority.High

#356 Update individual dg
  docs/DeveloperGuide.md
  src/main/java/seedu/us/among/commons/util/HeaderUtil.java
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/logic/parser/AddCommandParser.java
  src/main/java/seedu/us/among/logic/parser/EditCommandParser.java
  src/main/java/seedu/us/among/logic/parser/ParserUtil.java
  src/main/java/seedu/us/among/logic/parser/RunCommandParser.java
  src/main/java/seedu/us/among/logic/request/Request.java
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
  src/main/java/seedu/us/among/model/header/Header.java
  src/main/java/seedu/us/among/model/util/SampleDataUtil.java
  src/main/java/seedu/us/among/storage/JsonAdaptedEndpoint.java
  src/main/java/seedu/us/among/storage/JsonAdaptedHeader.java
  src/test/java/seedu/us/among/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/ParserUtilTest.java
  src/test/java/seedu/us/among/model/header/HeaderTest.java
  src/test/java/seedu/us/among/testutil/EditEndpointDescriptorBuilder.java
  src/test/java/seedu/us/among/testutil/EndpointBuilder.java
  src/test/java/seedu/us/among/testutil/EndpointUtil.java
Labels: JUST MERGE IT!!!, priority.High

#362 Chore: enable assertions in build.gradle
  build.gradle
Labels: JUST MERGE IT!!!, priority.High

#363 UI improvements: added ascii text
  src/main/java/seedu/us/among/ui/ResultDisplay.java
Labels: JUST MERGE IT!!!, priority.Low

#364 Fix test cases for send, run and imposterParser
  src/main/java/seedu/us/among/logic/parser/ParserUtil.java
  src/main/java/seedu/us/among/logic/parser/RunCommandParser.java
  src/main/java/seedu/us/among/model/endpoint/Address.java
  src/test/java/seedu/us/among/logic/parser/ImposterParserTest.java
  src/test/java/seedu/us/among/logic/parser/RunCommandParserTest.java
Labels: JUST MERGE IT!!!, priority.High

#366 Refactor: use square unicode chars for response title
  src/main/java/seedu/us/among/ui/ResultDisplay.java
Labels: JUST MERGE IT!!!, priority.High

#367 Developer guide update
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
  src/main/java/seedu/us/among/ui/ResultDisplay.java
Labels: JUST MERGE IT!!!, priority.Medium

#369 Feat: add outline to focused component for clarity
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/EndpointListPanel.fxml
  src/main/resources/view/ImposterTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/ResultDisplay.fxml
Labels: JUST MERGE IT!!!, priority.High

#370 Find command
  src/main/java/seedu/us/among/logic/parser/FindCommandParser.java
  src/test/java/seedu/us/among/model/endpoint/AddressContainsKeywordsPredicateTest.java
  src/test/java/seedu/us/among/model/endpoint/DataContainsKeywordsPredicateTest.java
  src/test/java/seedu/us/among/model/endpoint/EndPointContainsKeywordsPredicateTest.java
  src/test/java/seedu/us/among/model/endpoint/HeadersContainsKeywordsPredicateTest.java
  src/test/java/seedu/us/among/model/endpoint/TagsContainsKeywordsPredicateTest.java
Labels: JUST MERGE IT!!!, priority.High

#373 Fix: fix minor errors with request feature diagrams
  docs/diagrams/RequestActivityDiagram.puml
  docs/diagrams/RequestSequenceDiagram.puml
  docs/images/RequestActivityDiagram.png
  docs/images/RequestSequenceDiagram.png
Labels: JUST MERGE IT!!!, priority.Medium

#375 Fix diagrams
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ModelSequenceDiagram.puml
  docs/diagrams/RemoveSequenceDiagram.puml
  docs/images/BetterModelClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/RemoveSequenceDiagram.png
Labels: JUST MERGE IT!!!, priority.High, severity.Low, type.Task

#377 Fix: fix diagram size for request feature
  docs/DeveloperGuide.md
  docs/images/RequestActivityDiagram.png
  docs/images/RequestSequenceDiagram.png
Labels: JUST MERGE IT!!!, priority.Medium

#380 Docs: More diagram fixes
  docs/DeveloperGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/AddActivityDiagram.png
  docs/images/UiClassDiagram.png
Labels: JUST MERGE IT!!!, priority.High, severity.Low, type.Task

#382 Docs: update and tidy up UGDG for peer review
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_sass/minima/_layout.scss
  docs/diagrams/UiClassDiagram.puml
  docs/images/ArchitectureDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/UiClassDiagram.png
  docs/index.md
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/main/java/seedu/us/among/ui/Theme.java
Labels: JUST MERGE IT!!!, priority.High

#386 Docs: fix endpoint diagram and add some todos from peer review
  docs/DeveloperGuide.md
  docs/diagrams/EndpointClassDiagram.puml
  docs/images/EndpointClassDiagram.png
Labels: JUST MERGE IT!!!, priority.High, severity.High

#388 Docs: update styling for about us page and add PPP for tjtanjin
  docs/AboutUs.md
  docs/_includes/head.html
  docs/assets/css/style.scss
  docs/images/github-highres-icon.png
  docs/images/home-icon.png
  docs/images/portfolio-icon.png
  docs/team/tjtanjin.md
Labels: JUST MERGE IT!!!, priority.Medium

#390 Docs: minor content update to developer guide
  docs/DeveloperGuide.md
Labels: JUST MERGE IT!!!, priority.High

#384 UI: list ui enhancement
  src/main/java/seedu/us/among/logic/commands/CommandResult.java
  src/main/java/seedu/us/among/logic/commands/ExitCommand.java
  src/main/java/seedu/us/among/logic/commands/HelpCommand.java
  src/main/java/seedu/us/among/logic/commands/ListCommand.java
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/main/java/seedu/us/among/ui/ResultDisplay.java
  src/main/resources/images/imPosterEmptyList.png
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/us/among/logic/commands/CommandResultTest.java
  src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
  src/test/java/seedu/us/among/logic/commands/ExitCommandTest.java
  src/test/java/seedu/us/among/logic/commands/HelpCommandTest.java
  src/test/java/seedu/us/among/logic/commands/ListCommandTest.java
Labels: JUST MERGE IT!!!, priority.Medium, severity.Low, type.Enhancement

#392 Fix: fix image links for icons in AboutUs
  docs/AboutUs.md
Labels: JUST MERGE IT!!!, priority.Medium

#393 UI: Replace menu with static banner
  src/main/java/seedu/us/among/ui/CommandBox.java
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/ImposterTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/fonts/AmaticSC-Bold.ttf
Labels: priority.Medium

#395 Remove a space in front of Response body wording
  src/main/java/seedu/us/among/ui/ResultDisplay.java
Labels: priority.High

#399 Docs: improve user guide based on peer feedback
  docs/UserGuide.md
  docs/assets/css/style.scss
  docs/images/Ui.png
  docs/images/commands/add.png
  docs/images/commands/clear.png
  docs/images/commands/edit.png
  docs/images/commands/find.png
  docs/images/commands/list.png
  docs/images/commands/remove.png
  docs/images/commands/run.png
  docs/images/commands/send.png
  docs/images/commands/show.png
  docs/images/commands/toggle.png
  docs/images/red_box.png
  docs/images/startscreen.png
Labels: JUST MERGE IT!!!, priority.High

#402 Minor fixes for user guide
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High, severity.High

#403 Feature: Add ctrl + up-arrow feature to get last valid command
  docs/UserGuide.md
  src/main/java/seedu/us/among/ui/CommandBox.java
Labels: priority.High, severity.High

#404 UI improvements
  docs/team/ong6.md
  src/main/java/seedu/us/among/logic/commands/ListCommand.java
  src/main/java/seedu/us/among/ui/EndpointListPanel.java
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/main/java/seedu/us/among/ui/ThemeType.java
  src/main/resources/view/EndpointListPanel.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MaterialTheme.css
  src/main/resources/view/ResultDisplay.fxml
Labels: priority.High

#408 Docs: tidy up user guide for consult
  docs/UserGuide.md
  docs/images/helpMessage.png
  docs/images/startscreen.png
Labels: JUST MERGE IT!!!, priority.High

#409 UI: Fix wrong theme gifs in new material theme
  src/main/java/seedu/us/among/ui/ResultDisplay.java
Labels: JUST MERGE IT!!!, priority.Medium

#412 Docs: add workflow guide to project page
  docs/WorkflowGuide.md
  docs/_config.yml
  docs/images/imPosterWorkGuide.png
Labels: JUST MERGE IT!!!, priority.Medium

#413 Fix keycode issue with Mac OS
  docs/UserGuide.md
  src/main/java/seedu/us/among/ui/CommandBox.java
Labels: priority.High

#423 Update personal contribution page & minor fix on UG
  docs/UserGuide.md
  docs/team/tlylt.md
Labels: priority.High

#424 Refactor CommandResult constructors
  src/main/java/seedu/us/among/logic/commands/CommandResult.java
  src/main/java/seedu/us/among/logic/commands/ExitCommand.java
  src/main/java/seedu/us/among/logic/commands/HelpCommand.java
  src/main/java/seedu/us/among/logic/commands/ListCommand.java
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/test/java/seedu/us/among/logic/commands/CommandResultTest.java
  src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
  src/test/java/seedu/us/among/logic/commands/ExitCommandTest.java
  src/test/java/seedu/us/among/logic/commands/HelpCommandTest.java
Labels: priority.High

#426 Chore: update sample endpoints both in code and userguide
  docs/UserGuide.md
  src/main/java/seedu/us/among/logic/request/EndpointCaller.java
  src/main/java/seedu/us/among/model/util/SampleDataUtil.java
  src/main/java/seedu/us/among/ui/CommandBox.java
Labels: JUST MERGE IT!!!, priority.High

#427 Docs: use unannotated screenshot for index page
  docs/images/Ui.png
  src/main/java/seedu/us/among/model/util/SampleDataUtil.java
Labels: JUST MERGE IT!!!, priority.High

#428 Test: Edit remove test cases
  docs/team/julietteoh.md
  src/main/java/seedu/us/among/model/endpoint/Address.java
  src/main/java/seedu/us/among/storage/JsonAdaptedEndpoint.java
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
  src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
  src/test/java/seedu/us/among/logic/commands/EditEndpointDescriptorTest.java
  src/test/java/seedu/us/among/logic/parser/CommandParserTestUtil.java
  src/test/java/seedu/us/among/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/us/among/testutil/EditEndpointDescriptorBuilder.java
Labels: priority.High

#430 Docs: minor update to readme and index page
  README.md
  docs/index.md
Labels: JUST MERGE IT!!!, priority.High

#432 Fix: minor fix to model and storage component diagrams in DG
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
Labels: JUST MERGE IT!!!, priority.High

#434 Update help window content
  docs/images/helpMessage.png
  src/main/java/seedu/us/among/ui/UserGuide.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/us/among/ui/UserGuideTest.java
Labels: JUST MERGE IT!!!, priority.High

#436 User Guide update
  docs/UserGuide.md
  src/main/java/seedu/us/among/logic/commands/ToggleCommand.java
Labels: JUST MERGE IT!!!, priority.High

#438 Update some GET APIs
  docs/UserGuide.md
Labels: priority.High
