Repository AY2021S2-CS2103T-T12-4/tp, pull requests merged in 2021-04, with the labels that each got.

#451 Cleanup code comments
  docs/UserGuide.md
  docs/images/commands/add.png
  src/main/java/seedu/us/among/logic/request/EndpointCaller.java
  src/main/java/seedu/us/among/model/endpoint/Data.java
  src/main/java/seedu/us/among/model/endpoint/Response.java
  src/main/java/seedu/us/among/ui/CommandBox.java
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/test/java/seedu/us/among/model/endpoint/DataTest.java
  src/test/java/seedu/us/among/model/endpoint/EndpointTest.java
Labels: JUST MERGE IT!!!, priority.High

#455 Docs: add and update sample endpoints
  docs/UserGuide.md
Labels: JUST MERGE IT!!!, priority.High

#453 Docs: add required sections to appendix
  docs/DeveloperGuide.md
Labels: JUST MERGE IT!!!, priority.High

#456 Update version number
  src/main/java/seedu/us/among/ImPoster.java
Labels: priority.High

#458 Small changes
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/us/among/testutil/TypicalEndpoints.java
Labels: JUST MERGE IT!!!, priority.Low

#460 Small changes
  src/main/java/seedu/us/among/commons/core/GuiSettings.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/us/among/storage/JsonUserPrefsStorageTest.java
Labels: JUST MERGE IT!!!, priority.High

#463 Docs: tidy up user guide for PE dry run
  docs/UserGuide.md
Labels: JUST MERGE IT!!!, priority.High

#465 Update links to website
  docs/UserGuide.md
Labels: JUST MERGE IT!!!, priority.High

#467 Docs: fix broken links in UG
  docs/UserGuide.md
Labels: JUST MERGE IT!!!, priority.High

#464 Docs: Include toggle command implementation and sequence diagram
  docs/DeveloperGuide.md
  docs/diagrams/ToggleSequenceDiagram.puml
  docs/images/ToggleSequenceDiagram.png
Labels: JUST MERGE IT!!!, priority.Medium

#536 Fixes #516, Update GUI theme loading
  src/main/java/seedu/us/among/commons/core/GuiSettings.java
  src/main/java/seedu/us/among/commons/core/Messages.java
  src/main/java/seedu/us/among/ui/ResultDisplay.java
Labels: JUST MERGE IT!!!, priority.High, type.Bug

#538 Docs: fix minor details in tjtanjin ppp
  docs/team/tjtanjin.md
Labels: JUST MERGE IT!!!, priority.High

#540 Chore: cleanup storage and logic diagrams after upstream merge
  docs/diagrams/StorageClassDiagram.puml
  docs/images/LogicClassDiagram.png
  docs/images/StorageClassDiagram.png
Labels: JUST MERGE IT!!!, priority.High

#535 Small changes
  docs/UserGuide.md
  src/main/java/seedu/us/among/logic/commands/AddCommand.java
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
Labels: priority.High, type.Bug

#544 Docs: touchup UG details based on PE-D feedback
  docs/UserGuide.md
Labels: JUST MERGE IT!!!, priority.High

#545 Docs: Update UG highlighting and add more tips for clarity
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddActivityDiagram.puml
  docs/images/AddActivityDiagram.png
Labels: priority.High

#542 Fix: trim API response to enforce max 100000 chars
  src/main/java/seedu/us/among/ui/ResultDisplay.java
Labels: JUST MERGE IT!!!, priority.High

#546 Docs: Fix formatting and broken hyperlink in UG
  docs/UserGuide.md
Labels: priority.High

#543 Fix: standardise connection/unknownhost error messages to minimize confusion
  src/main/java/seedu/us/among/commons/core/Messages.java
  src/main/java/seedu/us/among/logic/request/EndpointCaller.java
Labels: JUST MERGE IT!!!, priority.High

#541 Fix help window issues
  src/main/java/seedu/us/among/ui/HelpWindow.java
  src/main/java/seedu/us/among/ui/UserGuide.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/us/among/ui/UserGuideTest.java
Labels: priority.High

#549 Fix: fix themed gifs not loading correctly
  src/main/java/seedu/us/among/commons/core/GuiSettings.java
  src/main/java/seedu/us/among/model/UserPrefs.java
  src/main/java/seedu/us/among/ui/ResultDisplay.java
Labels: JUST MERGE IT!!!, priority.High

#550 Fix: remove orange speck in image
  src/main/resources/images/imPosterEmptyList.png
Labels: JUST MERGE IT!!!, priority.High

#551 UG update addressing the Find command and Edit commands
  docs/UserGuide.md
Labels: JUST MERGE IT!!!, priority.High, type.Bug

#553 Addressing more bugs
  docs/Gemfile.lock
  docs/UserGuide.md
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/model/endpoint/Address.java
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
  src/main/java/seedu/us/among/model/tag/Tag.java
Labels: JUST MERGE IT!!!, priority.High, type.Bug

#554 Edit does not refresh the endpoint list.
  docs/UserGuide.md
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/model/Model.java
  src/main/java/seedu/us/among/model/ModelManager.java
  src/test/java/seedu/us/among/logic/commands/AddCommandTest.java
  src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
Labels: JUST MERGE IT!!!, priority.High, type.Bug

#555 Update integer parsing and show command fixes
  src/main/java/seedu/us/among/commons/core/Messages.java
  src/main/java/seedu/us/among/commons/util/StringUtil.java
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/logic/commands/RemoveCommand.java
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/commands/ShowCommand.java
  src/main/java/seedu/us/among/logic/parser/ParserUtil.java
  src/main/java/seedu/us/among/logic/parser/ShowCommandParser.java
  src/test/java/seedu/us/among/logic/LogicManagerTest.java
  src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
  src/test/java/seedu/us/among/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/us/among/logic/commands/SendCommandTest.java
  src/test/java/seedu/us/among/logic/commands/ShowCommandTest.java
  src/test/java/seedu/us/among/logic/parser/ParserUtilTest.java
  src/test/java/seedu/us/among/logic/parser/ShowCommandParserTest.java
Labels: priority.High

#556 Fix index error for remove and send command
  docs/UserGuide.md
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/logic/commands/RemoveCommand.java
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/us/among/logic/parser/SendCommandParser.java
  src/test/java/seedu/us/among/logic/LogicManagerTest.java
  src/test/java/seedu/us/among/logic/commands/RemoveCommandTest.java
  src/test/java/seedu/us/among/logic/commands/SendCommandTest.java
  src/test/java/seedu/us/among/logic/parser/RemoveCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/SendCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/ShowCommandParserTest.java
Labels: priority.High

#557 Edit list command message to be less wordy
  docs/UserGuide.md
  src/main/java/seedu/us/among/logic/commands/ListCommand.java
Labels: priority.Medium

#562 Improve find command in UG
  docs/UserGuide.md
Labels: JUST MERGE IT!!!, priority.High

#564 Update RunCommandParser and fix relevant error messages
  docs/UserGuide.md
  src/main/java/seedu/us/among/commons/core/Messages.java
  src/main/java/seedu/us/among/logic/parser/ParserUtil.java
  src/main/java/seedu/us/among/logic/parser/RunCommandParser.java
  src/main/java/seedu/us/among/model/endpoint/Address.java
  src/test/java/seedu/us/among/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/RunCommandParserTest.java
Labels: priority.High

#565 PPP Draft
  docs/team/ong6.md
Labels: JUST MERGE IT!!!, priority.Low

#566 Fix error messages
  docs/UserGuide.md
  docs/team/julietteoh.md
  src/main/java/seedu/us/among/commons/core/Messages.java
  src/main/java/seedu/us/among/logic/commands/AddCommand.java
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/logic/commands/FindCommand.java
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/java/seedu/us/among/logic/parser/EditCommandParser.java
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
  src/main/java/seedu/us/among/model/endpoint/Response.java
  src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
  src/test/java/seedu/us/among/logic/parser/EditCommandParserTest.java
Labels: priority.Medium, severity.Medium

#572 UI: Adding flowPane display for add, edit and show
  src/main/java/seedu/us/among/commons/core/GuiSettings.java
  src/main/java/seedu/us/among/commons/core/Messages.java
  src/main/java/seedu/us/among/logic/commands/AddCommand.java
  src/main/java/seedu/us/among/logic/commands/CommandResult.java
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/logic/commands/ShowCommand.java
  src/main/java/seedu/us/among/model/endpoint/Endpoint.java
  src/main/java/seedu/us/among/model/endpoint/Response.java
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/main/java/seedu/us/among/ui/ResultDisplay.java
  src/test/java/seedu/us/among/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
  src/test/java/seedu/us/among/logic/commands/EditCommandTest.java
  src/test/java/seedu/us/among/storage/JsonUserPrefsStorageTest.java
Labels: priority.High, type.Bug

#571 Update usage of GET and edit examples
  docs/UserGuide.md
  src/main/java/seedu/us/among/logic/commands/AddCommand.java
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/logic/commands/FindCommand.java
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/resources/view/HelpWindow.fxml
Labels: priority.High

#574 Chore: update release version to match v1.4
  src/main/java/seedu/us/among/ImPoster.java
Labels: JUST MERGE IT!!!, priority.High

#575 Update minimun size
  src/main/resources/view/MainWindow.fxml
Labels: JUST MERGE IT!!!, priority.High

#576 Docs: Developer Guide formatting
  docs/DeveloperGuide.md
  docs/diagrams/ToggleSequenceDiagram.puml
  docs/images/FindActivityDiagram.png
  docs/images/ToggleSequenceDiagram.png
Labels: JUST MERGE IT!!!, priority.High

#577 Docs: update commands section overview and help screenshot
  docs/UserGuide.md
  docs/images/helpMessage.png
Labels: JUST MERGE IT!!!, priority.High

#580 Update PPP section and standardize Mac/MacOS to macOS)
  docs/UserGuide.md
  docs/WorkflowGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
  docs/images/add-remark/$Remark.png
  docs/images/add-remark/CommandInterface.png
  docs/images/add-remark/ContextMenu.png
  docs/images/add-remark/CreateTest.png
  docs/images/add-remark/GradleRun.png
  docs/images/add-remark/ParserInterface.png
  docs/images/add-remark/RemarkBound.png
  docs/images/add-remark/RemarkComplete.png
  docs/images/add-remark/RemarkFailureOutput.png
  docs/images/add-remark/RemarkHello.png
  docs/images/add-remark/RemarkNotImplemented.png
  docs/team/tlylt.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
Labels: priority.High

#588 Docs: Add details to Appendix H
  docs/DeveloperGuide.md
Labels: JUST MERGE IT!!!, priority.High

#591 Edit UG to fix any minor issues
  docs/UserGuide.md
Labels: priority.High

#594 Quick fix UG
  docs/UserGuide.md
Labels: priority.High

#595 Update minimum windows size
  src/main/java/seedu/us/among/commons/core/GuiSettings.java
  src/main/java/seedu/us/among/commons/core/Messages.java
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/resources/view/MainWindow.fxml
Labels: JUST MERGE IT!!!, priority.High

#596 Fix formatting
  docs/team/tlylt.md
Labels: priority.High

#597 Minor update to my ppp page
  docs/team/tlylt.md
Labels: priority.High

#602 Clean up for DG
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Testing.md
  docs/index.md
Labels: priority.High, severity.Low

#603 Docs: tidy up use cases and NFR
  docs/DeveloperGuide.md
Labels: JUST MERGE IT!!!, priority.High

#606 Update appendix E and F
  docs/DeveloperGuide.md
  docs/WorkflowGuide.md
Labels: priority.High

#601 Refactor: tidy up error messages for all commands and decrease min size
  docs/UserGuide.md
  docs/images/commands/add.png
  docs/images/commands/clear.png
  docs/images/commands/edit.png
  docs/images/commands/find.png
  docs/images/commands/find1.png
  docs/images/commands/find2.png
  docs/images/commands/find3.png
  docs/images/commands/list.png
  docs/images/commands/remove.png
  docs/images/commands/run.png
  docs/images/commands/send.png
  docs/images/commands/show.png
  docs/images/startscreen.png
  src/main/java/seedu/us/among/commons/core/Messages.java
  src/main/java/seedu/us/among/logic/commands/AddCommand.java
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/logic/commands/FindCommand.java
  src/main/java/seedu/us/among/logic/commands/RemoveCommand.java
  src/main/java/seedu/us/among/logic/commands/RunCommand.java
  src/main/java/seedu/us/among/logic/commands/SendCommand.java
  src/main/java/seedu/us/among/logic/commands/ShowCommand.java
  src/main/java/seedu/us/among/logic/commands/ToggleCommand.java
  src/main/java/seedu/us/among/logic/parser/EditCommandParser.java
  src/main/java/seedu/us/among/logic/parser/ParserUtil.java
  src/main/java/seedu/us/among/logic/parser/RemoveCommandParser.java
  src/main/java/seedu/us/among/logic/parser/SendCommandParser.java
  src/main/java/seedu/us/among/logic/parser/ShowCommandParser.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/us/among/logic/commands/ShowCommandTest.java
  src/test/java/seedu/us/among/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/ParserUtilTest.java
  src/test/java/seedu/us/among/logic/parser/RemoveCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/SendCommandParserTest.java
  src/test/java/seedu/us/among/logic/parser/ShowCommandParserTest.java
Labels: JUST MERGE IT!!!, priority.High

#614 Remove command: Flowpane addition
  docs/DeveloperGuide.md
  src/main/java/seedu/us/among/logic/commands/RemoveCommand.java
  src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
  src/test/java/seedu/us/among/logic/commands/RemoveCommandTest.java
Labels: JUST MERGE IT!!!, priority.High

#616 Docs: update DG test cases and resize diagrams
  docs/DeveloperGuide.md
Labels: JUST MERGE IT!!!, priority.High

#618 PPP update
  docs/team/ong6.md
Labels: JUST MERGE IT!!!, priority.High

#619 Dg update send & run feature as well as adding manual testing: show, list
  docs/DeveloperGuide.md
  docs/diagrams/RunActivityDiagram.puml
  docs/diagrams/RunSequenceDiagram.puml
  docs/diagrams/SendSequenceDiagram.puml
  docs/images/RunActivityDiagram.png
  docs/images/RunSequenceDiagram.png
  docs/team/tlylt.md
Labels: JUST MERGE IT!!!, priority.High

#620 UI: Update endpoint after show command.
  src/main/java/seedu/us/among/logic/commands/AddCommand.java
  src/main/java/seedu/us/among/logic/commands/CommandResult.java
  src/main/java/seedu/us/among/logic/commands/EditCommand.java
  src/main/java/seedu/us/among/logic/commands/ShowCommand.java
  src/main/java/seedu/us/among/ui/EndpointListPanel.java
  src/main/java/seedu/us/among/ui/MainWindow.java
  src/test/java/seedu/us/among/logic/commands/CommandTestUtil.java
Labels: JUST MERGE IT!!!, priority.High

#621 DG: Appendix H implementation
  docs/DeveloperGuide.md
Labels: JUST MERGE IT!!!, priority.High

#622 Docs: touch up user guide details
  docs/UserGuide.md
  docs/images/commands/remove.png
  docs/images/startscreen.png
Labels: JUST MERGE IT!!!, priority.High

#625 Docs: Furnish up DG
  docs/DeveloperGuide.md
Labels: JUST MERGE IT!!!, priority.High

#624 Test: Wrote some find test cases
  docs/DeveloperGuide.md
  docs/team/julietteoh.md
  src/test/data/JsonSerializableEndpointListTest/typicalEndpointList.json
  src/test/java/seedu/us/among/logic/commands/FindCommandTest.java
  src/test/java/seedu/us/among/testutil/TypicalEndpoints.java
Labels: priority.Medium, severity.Low

#627 Docs: PPP update
  docs/team/nightraven49.md
Labels: JUST MERGE IT!!!

#628 Final UG update
  docs/UserGuide.md
Labels: JUST MERGE IT!!!, priority.High

#629 Docs: DG final revision
  docs/DeveloperGuide.md
Labels: priority.High

#631 Docs: update effort appendix and request feature
  docs/DeveloperGuide.md
Labels: JUST MERGE IT!!!, priority.High

#633 Docs: PPP update
  docs/team/nightraven49.md
Labels: JUST MERGE IT!!!

#634 Update DG + diagrams
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/FindActivityDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/ToggleSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
  docs/images/FindActivityDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/ToggleSequenceDiagram.png
  src/main/java/seedu/us/among/commons/core/GuiSettings.java
Labels: JUST MERGE IT!!!, priority.High

#637 Docs: finalise tjtanjin PPP
  docs/team/tjtanjin.md
Labels: JUST MERGE IT!!!, priority.High

#638 Bug fix
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/images/AddSequenceDiagram.png
Labels: JUST MERGE IT!!!, priority.High

#642 Chore: update code comments to adhere to code reuse policy
  src/main/java/seedu/us/among/Main.java
  src/main/java/seedu/us/among/commons/util/StringUtil.java
  src/main/java/seedu/us/among/model/endpoint/MethodType.java
  src/main/java/seedu/us/among/ui/ResultDisplay.java
  src/main/java/seedu/us/among/ui/ThemeType.java
Labels: JUST MERGE IT!!!, priority.High
